version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: "OTUS_DB"
      POSTGRES_USER: "student"
      POSTGRES_PASSWORD: "password"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5555:5432"