version: '3'

services:
  mysql_db:
    platform: linux/x86_64
    image: mysql:8.0.15
    restart: always
    environment:
      MYSQL_DATABASE: OTUS_DB_MYSQL
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./initdb/init.sql:/init.sql
      - ./custom.conf:/etc/mysql/conf.d
      - data:/var/lib/mysql
      - ./date/worker.csv:/worker.csv
    command:
      --init-file /init.sql
      --character-set-server=cp1251 --collation-server=cp1251_general_ci

volumes:
  data: